const images: any = [
  { id: 0, src: require("./DSC_1529.jpg"), title: "" },
  { id: 1, src: require("./DSC_1537.jpg"), title: "" },
  { id: 2, src: require("./DSC_1545.jpg"), title: "" },
  { id: 3, src: require("./DSC_1715.jpg"), title: "" },
  { id: 4, src: require("./DSC_1717.jpg"), title: "" },
  { id: 5, src: require("./DSC_1724.jpg"), title: "" },
  { id: 6, src: require("./DSC_1734.jpg"), title: "" },
  { id: 7, src: require("./DSC_1742.jpg"), title: "" },
  { id: 8, src: require("./DSC_1766.jpg"), title: "" },
  { id: 9, src: require("./DSC_1776.jpg"), title: "" },
  { id: 10, src: require("./DSC_1793.jpg"), title: "" },
  { id: 11, src: require("./DSC_1794.jpg"), title: "" },
  { id: 12, src: require("./DSC_1795.jpg"), title: "" },
  { id: 13, src: require("./DSC_1796.jpg"), title: "" },
  { id: 14, src: require("./DSC_1801.jpg"), title: "" },
  { id: 15, src: require("./DSC_1809.jpg"), title: "" },
  { id: 16, src: require("./DSC_1819.jpg"), title: "" },
  { id: 17, src: require("./DSC_1891.jpg"), title: "" },
  { id: 18, src: require("./DSC_1893.jpg"), title: "" },
  { id: 19, src: require("./DSC_1899.jpg"), title: "" },
  { id: 20, src: require("./DSC_1900.jpg"), title: "" },
  { id: 21, src: require("./DSC_1901.jpg"), title: "" },
];
export default images;
