const images: any = [
  { id: 0, src: require("./DSC_4673.jpg"), title: "" },
  { id: 1, src: require("./DSC_4674.jpg"), title: "" },
  { id: 2, src: require("./DSC_4694.jpg"), title: "" },
  { id: 3, src: require("./DSC_4699.jpg"), title: "" },
  { id: 4, src: require("./DSC_4700.jpg"), title: "" },
  { id: 5, src: require("./DSC_4702.jpg"), title: "" },
  { id: 6, src: require("./DSC_4704.jpg"), title: "" },
  { id: 7, src: require("./DSC_4708.jpg"), title: "" },
  { id: 8, src: require("./DSC_4730.jpg"), title: "" },
  { id: 9, src: require("./DSC_4736.jpg"), title: "" },
  { id: 10, src: require("./DSC_4739.jpg"), title: "" },
  { id: 11, src: require("./DSC_4744.jpg"), title: "" },
  { id: 12, src: require("./DSC_4745.jpg"), title: "" },
  { id: 13, src: require("./DSC_4756.jpg"), title: "" },
  { id: 14, src: require("./DSC_4761.jpg"), title: "" },
  { id: 15, src: require("./DSC_4771.jpg"), title: "" },
  { id: 16, src: require("./DSC_4783.jpg"), title: "" },
  { id: 17, src: require("./DSC_4785.jpg"), title: "" },
  { id: 18, src: require("./DSC_4787.jpg"), title: "" },
  { id: 19, src: require("./DSC_4788.jpg"), title: "" },
  { id: 20, src: require("./DSC_4806.jpg"), title: "" },
  { id: 21, src: require("./DSC_4815.jpg"), title: "" },
  { id: 22, src: require("./DSC_4821.jpg"), title: "" },
  { id: 23, src: require("./DSC_4826.jpg"), title: "" },
  { id: 24, src: require("./DSC_4838.jpg"), title: "" },
  { id: 25, src: require("./DSC_4839.jpg"), title: "" },
  { id: 26, src: require("./DSC_4848.jpg"), title: "" },
  { id: 27, src: require("./DSC_4852.jpg"), title: "" },
  { id: 28, src: require("./IMG_4262.jpg"), title: "" },
];
export default images;
