const images: any = [
  { id: 0, src: require("./DSC_1220.jpg"), title: "" },
  { id: 1, src: require("./DSC_1283.jpg"), title: "" },
  { id: 2, src: require("./DSC_1303.jpg"), title: "" },
  { id: 3, src: require("./DSC_1350.jpg"), title: "" },
  { id: 4, src: require("./DSC_1353.jpg"), title: "" },
  { id: 5, src: require("./DSC_1506.jpg"), title: "" },
  { id: 6, src: require("./DSC_1581.jpg"), title: "" },
  { id: 7, src: require("./DSC_1598.jpg"), title: "" },
  { id: 8, src: require("./DSC_1633.jpg"), title: "" },
  { id: 9, src: require("./DSC_1697.jpg"), title: "" },
  { id: 10, src: require("./DSC_1747.jpg"), title: "" },
  { id: 11, src: require("./DSC_1786.jpg"), title: "" },
  { id: 12, src: require("./DSC_1994.jpg"), title: "" },
  { id: 13, src: require("./DSC_2543.jpg"), title: "" },
  { id: 14, src: require("./DSC_2602.jpg"), title: "" },
  { id: 15, src: require("./DSC_2653.jpg"), title: "" },
  { id: 16, src: require("./DSC_2930.jpg"), title: "" },
  { id: 17, src: require("./DSC_2941.jpg"), title: "" },
  { id: 18, src: require("./DSC_2978.jpg"), title: "" },
  { id: 19, src: require("./DSC_3029.jpg"), title: "" },
  { id: 20, src: require("./DSC_3509.jpg"), title: "" },
  { id: 21, src: require("./DSC_3514.jpg"), title: "" },
];
export default images;
