const images: any = [
  { id: 0, src: require("./DSC_6089.jpg"), title: "" },
  { id: 1, src: require("./DSC_6097.jpg"), title: "" },
  { id: 2, src: require("./DSC_6098.jpg"), title: "" },
  { id: 3, src: require("./DSC_6110.jpg"), title: "" },
  { id: 4, src: require("./DSC_6114.jpg"), title: "" },
  { id: 5, src: require("./DSC_6127.jpg"), title: "" },
  { id: 6, src: require("./DSC_6128.jpg"), title: "" },
  { id: 7, src: require("./DSC_6141.jpg"), title: "" },
  { id: 8, src: require("./DSC_6147.jpg"), title: "" },
  { id: 9, src: require("./DSC_6156.jpg"), title: "" },
  { id: 10, src: require("./DSC_6160.jpg"), title: "" },
  { id: 11, src: require("./DSC_6165.jpg"), title: "" },
  { id: 12, src: require("./DSC_6166.jpg"), title: "" },
  { id: 13, src: require("./DSC_6170.jpg"), title: "" },
  { id: 14, src: require("./DSC_6172.jpg"), title: "" },
  { id: 15, src: require("./DSC_6189.jpg"), title: "" },
  { id: 16, src: require("./DSC_6197.jpg"), title: "" },
  { id: 17, src: require("./DSC_6226.jpg"), title: "" },
  { id: 18, src: require("./DSC_6230.jpg"), title: "" },
  { id: 19, src: require("./DSC_6231.jpg"), title: "" },
  { id: 20, src: require("./DSC_6246.jpg"), title: "" },
  { id: 21, src: require("./DSC_6253.jpg"), title: "" },
];
export default images;
