const images: any = [
  {
    src: require("./titles/DSC_0801.jpg"),
    title: "Mammoth",
    date: "November 2020",
    path: "/2020/mammoth",
  },
  {
    src: require("./titles/DSC_0627.jpg"),
    title: "Torrey Pines State Reserve",
    date: "November 2020",
    path: "/2020/torreypines",
  },
  {
    src: require("./titles/DSC_0382.jpg"),
    title: "Mammoth Lakes",
    date: "September 2020",
    path: "/2020/mammothlakes",
  },
  {
    src: require("./titles/DSC_0267.jpg"),
    title: "Sunset Cliffs",
    date: "August 2020",
    path: "/2020/sunsetcliffs",
  },
  {
    src: require("./titles/DSC_0152.jpg"),
    title: "Grand Canyon",
    date: "July 2020",
    path: "/2020/grandcanyon",
  },
  {
    src: require("./titles/DSC_0079.jpg"),
    title: "Zion National Park",
    date: "July 2020",
    path: "/2020/zion",
  },
  {
    src: require("./titles/DSC_9907.jpg"),
    title: "Bryce Canyon National Park",
    date: "July 2020",
    path: "/2020/brycecanyon",
  },
  {
    src: require("./titles/DSC_9831.jpg"),
    title: "Cross Country Road Trip",
    date: "July 2020",
    path: "/2020/crosscountry",
  },
  {
    src: require("./titles/DSC_9451.jpg"),
    title: "Kancamagus",
    date: "June 2020",
  },
  {
    src: require("./titles/DSC_9371.jpg"),
    title: "Mt. Washington",
    date: "June 2020",
    path: "/2020/mtwashington",
  },
  {
    src: require("./titles/DSC_8475.jpg"),
    title: "Alberta",
    date: "March 2020",
    path: "/2020/alberta",
  },
  {
    src: require("./titles/DSC_8450.jpg"),
    title: "Mammoth",
    date: "December 2019",
    path: "/2019/mammoth",
  },
  {
    src: require("./titles/DSC_6430.jpg"),
    title: "Isle of Skye",
    date: "May 2019",
    path: "/2019/isleofskye",
  },
  {
    src: require("./titles/DSC_5851.jpg"),
    title: "Pisa",
    date: "April 2019",
    path: "/2019/pisa",
  },
  {
    src: require("./titles/DSC_5557.jpg"),
    title: "Cinque Terre",
    date: "April 2019",
    path: "/2019/cinqueterre",
  },
  {
    src: require("./titles/DSC_5394.jpg"),
    title: "Malaga",
    date: "April 2019",
    path: "/2019/malaga",
  },
  {
    src: require("./titles/DSC_5159.jpg"),
    title: "St. Andrews",
    date: "March 2019",
    path: "/2019/standrews",
  },
  {
    src: require("./titles/DSC_4938.jpg"),
    title: "London",
    date: "March 2019",
    path: "/2019/london",
  },
  {
    src: require("./titles/DSC_4913.jpg"),
    title: "Stockholm",
    date: "February 2019",
    path: "/2019/stockholm",
  },
  {
    src: require("./titles/DSC_4848.jpg"),
    title: "North Berwick",
    date: "January 2019",
    path: "/2019/northberwick",
  },
  {
    src: require("./titles/DSC_2741.jpg"),
    title: "Chris Craft Boat Show",
    date: "July 2018",
    path: "/2018/chriscraft",
  },
  {
    src: require("./titles/DSC_2655.jpg"),
    title: "Cabot Cliffs",
    date: "July 2018",
    path: "/2018/cabotcliffs",
  },
  {
    src: require("./titles/DSC_2510.jpg"),
    title: "Malibu",
    date: "July 2018",
    path: "/2018/malibu",
  },
  {
    src: require("./titles/DSC_9568.jpg"),
    title: "Sugarloaf",
    date: "March 2018",
    path: "/2018/sugarloaf",
  },
  {
    src: require("./titles/DSC_5210.jpg"),
    title: "Wood Island",
    date: "May 2017",
    path: "/2017/woodisland",
  },
  {
    src: require("./titles/DSC_3482.jpg"),
    title: "Yellowstone National Park",
    date: "March 2017",
    path: "/2017/yellowstone",
  },
  {
    src: require("./titles/DSC_0571.jpg"),
    title: "Sugarloaf Homecoming",
    date: "October 2016",
    path: "/2016/sugarloaf",
  },
  {
    src: require("./titles/DSC_2602.jpg"),
    title: "St. Vincent & the Grenadines",
    date: "March 2016",
    path: "/2016/stvincent",
  },
];
export default images;
