const images: any = [
  { id: 0, src: require("./DSC_5349.jpg"), title: "" },
  { id: 1, src: require("./DSC_5352.jpg"), title: "" },
  { id: 2, src: require("./DSC_5356.jpg"), title: "" },
  { id: 3, src: require("./DSC_5357.jpg"), title: "" },
  { id: 4, src: require("./DSC_5368.jpg"), title: "" },
  { id: 5, src: require("./DSC_5373.jpg"), title: "" },
  { id: 6, src: require("./DSC_5376.jpg"), title: "" },
  { id: 7, src: require("./DSC_5382.jpg"), title: "" },
  { id: 8, src: require("./DSC_5390.jpg"), title: "" },
  { id: 9, src: require("./DSC_5394.jpg"), title: "" },
  { id: 10, src: require("./DSC_5397.jpg"), title: "" },
  { id: 11, src: require("./DSC_5414.jpg"), title: "" },
  { id: 12, src: require("./DSC_5427.jpg"), title: "" },
  { id: 13, src: require("./DSC_5429.jpg"), title: "" },
  { id: 14, src: require("./DSC_5431.jpg"), title: "" },
  { id: 15, src: require("./DSC_5442.jpg"), title: "" },
  { id: 16, src: require("./DSC_5465.jpg"), title: "" },
  { id: 17, src: require("./DSC_5466.jpg"), title: "" },
  { id: 18, src: require("./DSC_5468.jpg"), title: "" },
  { id: 19, src: require("./DSC_5471.jpg"), title: "" },
  { id: 20, src: require("./DSC_5475.jpg"), title: "" },
];
export default images;
