const images: any = [
  { id: 0, src: require("./DSC_1254.jpg"), title: "" },
  { id: 1, src: require("./DSC_1255.jpg"), title: "" },
  { id: 2, src: require("./DSC_1267.jpg"), title: "" },
  { id: 3, src: require("./DSC_1338.jpg"), title: "" },
  { id: 4, src: require("./DSC_1369.jpg"), title: "" },
  { id: 5, src: require("./DSC_1378.jpg"), title: "" },
  { id: 6, src: require("./DSC_1380.jpg"), title: "" },
  { id: 7, src: require("./DSC_1381.jpg"), title: "" },
  { id: 8, src: require("./DSC_1391.jpg"), title: "" },
  { id: 9, src: require("./DSC_1392.jpg"), title: "" },
  { id: 10, src: require("./DSC_1395.jpg"), title: "" },
  { id: 11, src: require("./DSC_1408.jpg"), title: "" },
  { id: 12, src: require("./DSC_1409.jpg"), title: "" },
  { id: 13, src: require("./DSC_1414.jpg"), title: "" },
  { id: 14, src: require("./DSC_1417.jpg"), title: "" },
  { id: 15, src: require("./DSC_1421.jpg"), title: "" },
  { id: 16, src: require("./DSC_1429.jpg"), title: "" },
  { id: 17, src: require("./DSC_1432.jpg"), title: "" },
  { id: 18, src: require("./DSC_1441.jpg"), title: "" },
  { id: 19, src: require("./DSC_1445.jpg"), title: "" },
  { id: 20, src: require("./DSC_1449.jpg"), title: "" },
];
export default images;
