const images: any = [
  { id: 0, src: require("./DSC_5119.jpg"), title: "" },
  { id: 1, src: require("./DSC_5131.jpg"), title: "" },
  { id: 2, src: require("./DSC_5153.jpg"), title: "" },
  { id: 3, src: require("./DSC_5157.jpg"), title: "" },
  { id: 4, src: require("./DSC_5158.jpg"), title: "" },
  { id: 5, src: require("./DSC_5159.jpg"), title: "" },
  { id: 6, src: require("./DSC_5162.jpg"), title: "" },
  { id: 7, src: require("./DSC_5164.jpg"), title: "" },
  { id: 8, src: require("./DSC_5165.jpg"), title: "" },
  { id: 9, src: require("./DSC_5170.jpg"), title: "" },
  { id: 10, src: require("./DSC_5171.jpg"), title: "" },
  { id: 11, src: require("./DSC_5197.jpg"), title: "" },
  { id: 12, src: require("./DSC_5222.jpg"), title: "" },
  { id: 13, src: require("./DSC_5239.jpg"), title: "" },
  { id: 14, src: require("./DSC_5245.jpg"), title: "" },
  { id: 15, src: require("./DSC_5247.jpg"), title: "" },
  { id: 16, src: require("./DSC_5261.jpg"), title: "" },
  { id: 17, src: require("./DSC_5274.jpg"), title: "" },
  { id: 18, src: require("./DSC_5275.jpg"), title: "" },
  { id: 19, src: require("./DSC_5282.jpg"), title: "" },
  { id: 20, src: require("./DSC_5305.jpg"), title: "" },
  { id: 21, src: require("./DSC_5314.jpg"), title: "" },
  { id: 22, src: require("./DSC_5315.jpg"), title: "" },
  { id: 23, src: require("./DSC_5321.jpg"), title: "" },
  { id: 24, src: require("./DSC_5333.jpg"), title: "" },
  { id: 25, src: require("./DSC_5338.jpg"), title: "" },
];
export default images;
